#!/usr/bin/env python

from openrazer.client import DeviceManager

devicemgr = DeviceManager()

viper = None
for d in devicemgr.devices:
    if d.name == "Razer Viper Ultimate (Wireless)" or d.name == "Razer Viper Ultimate (Wired)":
        viper = d

if viper == None:
    print("N/A")
    exit

charging = ""
if viper.is_charging:
    charging = "y"

print(f"{charging} {viper.battery_level}")
